#!/bin/bash

export TMP_SPOOL="$(mktemp)" || exit 1
export TMP_ERR="$(mktemp)" || exit 1
trap 'rm -f ${TMP_SPOOL}* ${TMP_ERR}* ' EXIT

export SCRIPT_NAME=$(basename $0)
export SCRIPT_DIR=$(readlink -f  $(dirname $0))
export SPOOL_DIR="${SCRIPT_DIR}/spools"
export CONF_DIR=$"${SCRIPT_DIR}/conf"
export LIB_DIR="${SCRIPT_DIR}/lib"
export BIN_DIR="${SCRIPT_DIR}/bin"

export DOT_PROFILE="${SCRIPT_DIR}/.${SCRIPT_NAME}"
. ${DOT_PROFILE}
  
export MAILX=mailx
if [[ ! -z ${CUSTOM_MAILX} ]]; then MAILX=${CUSTOM_MAILX}; fi

export TIMESTAMP=$(date "+%Y%m%d_%H.%M.%S")
export SPOOL_NAMING_CONV=
export MOD_SPOOL_DIR=

export ENV_CONF=
export ENV=
export CATENA=

function usage
{  
  COUNT=$(ls -1 ${CONF_DIR}/env.* | grep -v ${CONF_DIR}/env.Template.PRO | wc -l )

  if [[ $COUNT -eq 0 ]]; then
    echo -e "#"
    esciMale "87" "Non e' ancora stato configurato alcun Environment.\n#          Per ulteriori informazioni consultare la sezione Configurazione su GitHub:\n#\n#          https://github.com/${FGMarrone}mapuricelli${FGReset}/${FGGiallo}jms_queue_report#configurazione${FGReset}"
    
  else
    echo -e "#"
    echo -e "#  - Parametri di Environment disponibili:"
    echo -e "#"
    
    ls -1 ${CONF_DIR}/env.* | grep -v ${CONF_DIR}/env.Template.PRO | awk -F"." '{print $2"."$3}' | sort -u | while read C
    do
      echo -e "#    $(basename ${0}) ${FGGiallo}-e${FGReset} ${FGVerdeChiaro}${C}${FGReset}"
    done
  
  fi
  
  trailer

  exit 999
}

function header
{
  echo -e
  echo -e "########################################################################"
  echo -e "############################ ${FGAzzurroChiaro}JMS Queue Report${FGReset} ##########################"
  echo -e "########################################################################"
}

function trailer
{
  echo -e "#"
  echo -e "########################################################################"
  echo -e ""
}

function dotEnvMissing
{
  echo -e "#"
  esciMale "87" "Il file di conf ${FGGiallo}${ENV}.${CATENA}${FGReset} non esiste"
}

function dotEnvInvalid
{
  echo -e "#"
  esciMale "87" "Nel file di conf ${FGGiallo}${ENV}.${CATENA}${FGReset} non viene valorizzato il path del ${FGGiallo}setDomainEnv.sh${FGReset}"
}

function esciMale
{
  # $1 Codice di exit
  # $2 Messaggio di exit
  # $3 Messaggio di errore d'origine
  
  echo -e "#  - ${FGRossoChiaro}Fail${FGReset}: ${2}"
  
  if [[ -n "${3}" ]]; then
    echo -e "#"
    echo ${3} | while read ERR
    do
      echo -e "#    ${FGRossoChiaro}* ${ERR}${FGReset}"
    done
  fi
  
  echo -e "#"
  echo -e "#  - Exit Code ${FGRossoChiaro}${1}${FGReset}"

  trailer
    
  exit ${1}
}

function go
{

  if [[ ${CATENA} != "" ]]; then
  
    echo -e "#"
    echo -e "#    * Environment: ${FGVerdeChiaro}${ENV}${FGReset}"
    echo -e "#    * Catena:      ${FGVerdeChiaro}${CATENA}${FGReset}"
    echo -e "#"
    echo -e "#  - Per tutte le Destinazioni presenti nei seguenti Moduli JMS:"
    echo -e "#"
	for MOD in "${MODULI_JMS_LIST[@]}"
    do
      echo -e "#    * ${FGVerdeChiaro}${MOD}${FGReset}"
	done
    echo -e "#"
    echo -e "#  - Estraggo i seguenti valori a Runtime:"
    echo -e "#"
    echo -e "#    * ${FGVerdeChiaro}Consumer correnti      ${FGReset}(Consumers Current Count)"
    echo -e "#    * ${FGVerdeChiaro}Numero max di consumer ${FGReset}(Consumers High Count)"
    echo -e "#    * ${FGVerdeChiaro}Consumer totali        ${FGReset}(Consumers Total Count)"
    echo -e "#    * ${FGVerdeChiaro}Messaggi correnti      ${FGReset}(Messages Current Count)"
    echo -e "#    * ${FGVerdeChiaro}Numero max di messaggi ${FGReset}(Messages High Count)"
    echo -e "#    * ${FGVerdeChiaro}Messaggi in sospeso    ${FGReset}(Messages Pending Count)"
    echo -e "#"

    # Lancio l'export dei dati tramite WLST
    java weblogic.WLST ${BIN_DIR}/export.py 2> ${TMP_ERR} 1>  /dev/null

	if [[ $? -ne 0 ]]; then esciMale 888 "Errore nell'esecuzione dello script WLST!" $(cat ${TMP_ERR}); fi

    echo -e "#"
    echo -e "#  - Estrazione completata, contenuti compressi e backuppati :"

    SPOOL_NAMING_CONV="${CATENA}_${TIMESTAMP}"
	
    for MOD in "${MODULI_JMS_LIST[@]}"
    do

      MOD_SPOOL_DIR=${SPOOL_DIR}/${CATENA}/${ENV}/${MOD}
      mkdir -p ${MOD_SPOOL_DIR}/
	  MOD_FILENAME=${MOD}_${SPOOL_NAMING_CONV}

      # Riordino e creo il .csv ufficiale
	  (head -n 1 ${TMP_SPOOL}_${MOD} && tail -n +2 ${TMP_SPOOL}_${MOD} | sort) > ${MOD_SPOOL_DIR}/${MOD_FILENAME}.csv

      # Creo la versione html
      ${BIN_DIR}/csv2html ${MOD_SPOOL_DIR}/${MOD_FILENAME}.csv > ${MOD_SPOOL_DIR}/${MOD_FILENAME}.html
	  sed -i "s/{{TITOLO}}/<h1>JMS Queue Report<\/h1>/" ${MOD_SPOOL_DIR}/${MOD_FILENAME}.html
	  sed -i "s/{{SOTTOTITOLO}}/<h3>(${ENV} - ${CATENA})<\/h3>/" ${MOD_SPOOL_DIR}/${MOD_FILENAME}.html
	  sed -i "s/{{TITOLETTO}}/<h2>${MOD}<\/h2>/" ${MOD_SPOOL_DIR}/${MOD_FILENAME}.html

      # Creo la versione ascii table
      cat ${MOD_SPOOL_DIR}/${MOD_FILENAME}.csv | column -t -s "|" > ${MOD_SPOOL_DIR}/${MOD_FILENAME}.txt

      # Comprimo il tutto
      (cd ${MOD_SPOOL_DIR}/ && zip -q $(basename ${MOD_SPOOL_DIR}/${MOD_FILENAME}).zip $(basename ${MOD_SPOOL_DIR}/${MOD_FILENAME}).*)
	  
      echo -e "#"
      echo -e "#    ${FGAzzurroChiaro}${MOD_SPOOL_DIR}/${FGReset}"
      echo -e "#"
      echo -e "#    --> ${FGVerdeChiaro}${MOD_FILENAME}.zip${FGReset}"

    done

    echo -e "#"
    echo -e "#  - Invio i dati in allegato via email ai seguenti destinatari:"
    echo -e "#"
    for DEST in "${DESTINATARI_LIST[@]}"
    do
      echo -e "#    * ${FGAzzurroChiaro}${DEST}${FGReset}"
    done
    
    ATTACHMENTS=
    for MOD in "${MODULI_JMS_LIST[@]}"
    do
      ATTACHMENTS="${ATTACHMENTS} -a ${MOD_SPOOL_DIR}/${MOD_FILENAME}.zip"
    done

    # Concateno gli allegati e mando mail
    ( 
      echo "Per ogni Coda JMS presente nei Moduli selezionati sono stati estratti i seguenti valori per tutte le Destinazioni possibili:"
      echo ""
      echo "  * Consumer correnti      (Consumers Current Count)"
      echo "  * Numero max di consumer (Consumers High Count)"
      echo "  * Consumer totali        (Consumers Total Count)"
      echo "  * Messaggi correnti      (Messages Current Count)"
      echo "  * Numero max di messaggi (Messages High Count)"
      echo "  * Messaggi in sospeso    (Messages Pending Count)"
      echo ""
      echo "In allegato i report prodotti."
      echo ""
      echo "Manuel"
      echo "347 7098296"
    ) | mailx ${ATTACHMENTS} -s "[${ENV} - ${CATENA}] JMS Queue Report" ${DESTINATARI}

    rm -f ${SPOOL_DIR}/*/*/*/*.csv
    rm -f ${SPOOL_DIR}/*/*/*/*.txt
    rm -f ${SPOOL_DIR}/*/*/*/*.html

  else
    usage
  fi
}







if [[ ! -f ${LIB_DIR}/colori.conf ]]; then
  echo -e "#"
  esciMale 666 "Impossibile trovare il file di conf\n#\n#          ${FGGiallo}${LIB_DIR}/colori.conf${FGReset}!"
else
  . ${LIB_DIR}/colori.conf
fi

header

if [[ $# -lt 1 ]]; then
  usage
fi







while getopts "he:" Option
do
  case $Option in
    e )
	  ENV=$(echo ${OPTARG} | cut -d. -f1)
	  CATENA=$(echo ${OPTARG} | cut -d. -f2)
      ;;
    * )
      usage
      ;;
    ? )
      usage
      ;;
  esac
done

if [[ -f ${CONF_DIR}/env.${ENV}.${CATENA} ]]; then

  ENV_CONF=${CONF_DIR}/env.${ENV}.${CATENA}
  . ${ENV_CONF}

  if [[ -z ${SETDOMAINENV_PATH} ]]; then
    dotEnvInvalid
  else
    . ${SETDOMAINENV_PATH} >/dev/null
  fi

  read -a MODULI_JMS_LIST <<< ${MODULI_JMS}
  read -a DESTINATARI_LIST <<< ${DESTINATARI}

  go
  
  trailer

else
  dotEnvMissing
fi
